local_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 1
  width: 6                        # The local map is of course shorter than the global one. Same meaning for the parameters, than by global coatmap
  height: 6
  origin_x: -3
  origin_y: -3
  static_map: false           
  rolling_window: true
  resolution: 0.1